### ISSUE TITLE
Bug---ActivityNotFoundException

### ISSUE THREAD

**Issue by IceNum** [Heyzap/facebook-audience-network-ane#3]
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=intent://?af_deeplink=true&campaign=CO_Clicks_Mercados_27.04.17&is_retargeting=true&media_source=Facebook flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1776)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
       at android.app.Activity.startActivityForResult(Activity.java:3801)
       at android.app.Activity.startActivityForResult(Activity.java:3755)
       at android.app.Activity.startActivity(Activity.java:4072)
       at android.app.Activity.startActivity(Activity.java:4040)
       at com.facebook.ads.internal.view.a.a$3.onClick(Unknown Source)
       at android.view.View.performClick(View.java:4768)
       at android.view.View$PerformClick.run(View.java:19692)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)

com.facebook.ads.internal.view.a.a$3.onClick 
This method need  "try_catch "

**Comment by ekilah** [comment]
It looks like maybe you are missing an activity declaration in your manifest?
